VirtoCommerce.CustomerModule.Web/Controllers/Api/CustomerModuleController.cs
VirtoCommerce.CustomerModule.Web/Scripts/blades/member-list.js
VirtoCommerce.CustomerModule.Web/Scripts/resources/members.js

VirtoCommerce/vc-platform#1223

Make bulk delete members

---

VirtoCommerce.CustomerModule.Web/Content/css/customer.css
VirtoCommerce.CustomerModule.Web/Scripts/blades/customer-detail.js
VirtoCommerce.CustomerModule.Web/Scripts/blades/customer-detail.tpl.html
VirtoCommerce.CustomerModule.Web/Scripts/blades/employee-detail.js
VirtoCommerce.CustomerModule.Web/Scripts/blades/employee-detail.tpl.html
VirtoCommerce.CustomerModule.Web/Scripts/customer.js
VirtoCommerce.CustomerModule.Web/VirtoCommerce.CustomerModule.Web.csproj
VirtoCommerce.CustomerModule.Web/module.manifest

964 list organizations

---

VirtoCommerce.CustomerModule.Data/Repositories/CustomerRepositoryImpl.cs
VirtoCommerce.CustomerModule.Data/Repositories/MemberRepositoryBase.cs

Related to issue VirtoCommerce/vc-platform#1258

Extend MemberRepository and CustomerRepositoryImpl with additional constructor

---

VirtoCommerce.CustomerModule.Data/Services/CommerceMembersServiceImpl.cs
VirtoCommerce.CustomerModule.Data/Services/MemberServiceBase.cs
VirtoCommerce.CustomerModule.Data/VirtoCommerce.CustomerModule.Data.csproj
VirtoCommerce.CustomerModule.Data/packages.config
VirtoCommerce.CustomerModule.Test/VirtoCommerce.CustomerModule.Test.csproj
VirtoCommerce.CustomerModule.Test/packages.config
VirtoCommerce.CustomerModule.Web/Module.cs
VirtoCommerce.CustomerModule.Web/VirtoCommerce.CustomerModule.Web.csproj
VirtoCommerce.CustomerModule.Web/packages.config

Raise MemberChangedEvent after adding, updating and deleting a member.

---

VirtoCommerce.CustomerModule.Data/Model/AddressDataEntity.cs

add possibility to update address name

add possibility to change address name

---

VirtoCommerce.CustomerModule.Web/Controllers/Api/CustomerModuleController.cs

Added missed non-polymorphic search & bulk operations

---

VirtoCommerce.CustomerModule.Data/Model/AddressDataEntity.cs

@tatarincev A few more missing fields on Customer `AddressDataEntity`, namely `Organization`.

Add missing fields from Address.Patch

---

VirtoCommerce.CustomerModule.Data/Services/MemberServiceBase.cs

Paged search ordering revision

---

src/VirtoCommerce.CustomerModule.Web/Controllers/Api/CustomerModuleController.cs

Beating bugs with actions results: OK and NoContent.

---

src/VirtoCommerce.CustomerModule.Data/Model/OrganizationEntity.cs

There was a mistake in copying Organization model instance to OrganizationEntity instance.

VP-1271 bug fixed. 

---

src/VirtoCommerce.CustomerModule.Web/Scripts/blades/employee-detail.tpl.html

https://virtocommerce.atlassian.net/browse/VP-1272

#VP-1272 EmployeeType is disabled

---

src/VirtoCommerce.CustomerModule.Data/Migrations/20200123133848_MemberRelationDeleteBehaviorCascade.Designer.cs
src/VirtoCommerce.CustomerModule.Data/Migrations/20200123133848_MemberRelationDeleteBehaviorCascade.cs
src/VirtoCommerce.CustomerModule.Data/Repositories/CustomerDbContext.cs
src/VirtoCommerce.CustomerModule.Data/VirtoCommerce.CustomerModule.Data.csproj

https://virtocommerce.atlassian.net/browse/VP-1273

#VP-1273 MemberRelation deletebehavior cascade

---

src/VirtoCommerce.CustomerModule.Data/Search/MemberIndexedSearchService.cs
src/VirtoCommerce.CustomerModule.Data/VirtoCommerce.CustomerModule.Data.csproj
src/VirtoCommerce.CustomerModule.Web/Module.cs
src/VirtoCommerce.CustomerModule.Web/VirtoCommerce.CustomerModule.Web.csproj
src/VirtoCommerce.CustomerModule.Web/module.manifest

Use searchRequestBuildersRegistrar for override existing request builders
Have to be merged after https://github.com/VirtoCommerce/vc-module-search/pull/12

vp-1419 Migrate CatalogPersonalization module to V3

---

VirtoCommerce.CustomerModule.Web/Content/customer.css
VirtoCommerce.CustomerModule.Web/Localizations/en.VirtoCommerce.Customer.json
VirtoCommerce.CustomerModule.Web/Scripts/blades/filter-detail.js
VirtoCommerce.CustomerModule.Web/Scripts/blades/filter-detail.tpl.html
VirtoCommerce.CustomerModule.Web/Scripts/blades/member-list.js
VirtoCommerce.CustomerModule.Web/Scripts/blades/member-list.tpl.html
VirtoCommerce.CustomerModule.Web/Scripts/customer.js
VirtoCommerce.CustomerModule.Web/Scripts/directives/customerSearch.js
VirtoCommerce.CustomerModule.Web/Scripts/directives/customerSearch.tpl.html
VirtoCommerce.CustomerModule.Web/VirtoCommerce.CustomerModule.Web.csproj
VirtoCommerce.CustomerModule.Web/module.manifest

VP-1279 Add filtering to Contacts blade

---

VirtoCommerce.CustomerModule.Web/Scripts/blades/member-list.tpl.html

Add No data to UI when the grid is empty.

VP-1633 Add No data to UI when grid is empty.

---

VirtoCommerce.CustomerModule.Web/Scripts/blades/member-list.js

Add a possibility to extend member list search criterial, at this moment we could not extend the search criteria similar like order list

feat: Add a possibility to extend member list search criteria

---

src/VirtoCommerce.CustomerModule.Web/Scripts/customer.js

VP-2048 Don't show widget if a user hasn't permission

VP-2048 Don't show widget if user hasn't permission

---

VirtoCommerce.CustomerModule.Web/Scripts/blades/member-detail.js

4040 Fix serialization problem

---

src/VirtoCommerce.CustomerModule.Data/Services/MemberService.cs

A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
A clear and concise description of what you want to happen.
Describe the technical details of realization provided by you.
Add any other context or screenshots about the feature request here.

VP-5334: Call clear cache before publish event

---

src/VirtoCommerce.CustomerModule.Web/Controllers/Api/CustomerModuleController.cs

VP-3293: Empty Contacts created after submit form with empty Email

---

samples/VirtoCommerce.CustomerSampleModule.Web/VirtoCommerce.CustomerSampleModule.Web.csproj
src/VirtoCommerce.CustomerModule.Core/ModuleConstants.cs
src/VirtoCommerce.CustomerModule.Core/VirtoCommerce.CustomerModule.Core.csproj
src/VirtoCommerce.CustomerModule.Data/VirtoCommerce.CustomerModule.Data.csproj
src/VirtoCommerce.CustomerModule.Web/VirtoCommerce.CustomerModule.Web.csproj
src/VirtoCommerce.CustomerModule.Web/module.manifest

Related to https://github.com/VirtoCommerce/vc-platform/pull/2090
Jira: https://virtocommerce.atlassian.net/browse/VP-5673

VP-5673: Fix page size positive only

---

src/VirtoCommerce.CustomerModule.Data/Search/Indexing/MemberDocumentBuilder.cs

Using default value for required properties and `"__null"` for empty values

VP-6207: Add all member dynamic properties to index

---

src/VirtoCommerce.CustomerModule.Core/Model/Member.cs
src/VirtoCommerce.CustomerModule.Core/ModuleConstants.cs
src/VirtoCommerce.CustomerModule.Data/Migrations/20210118155810_AddStatusPropertyToMember.Designer.cs
src/VirtoCommerce.CustomerModule.Data/Migrations/20210118155810_AddStatusPropertyToMember.cs
src/VirtoCommerce.CustomerModule.Data/Model/MemberEntity.cs
src/VirtoCommerce.CustomerModule.Data/Search/Indexing/MemberDocumentBuilder.cs
src/VirtoCommerce.CustomerModule.Web/Localizations/en.VirtoCommerce.Customer.json
src/VirtoCommerce.CustomerModule.Web/Localizations/ru.VirtoCommerce.Customer.json
src/VirtoCommerce.CustomerModule.Web/Scripts/blades/customer-detail.js
src/VirtoCommerce.CustomerModule.Web/Scripts/blades/customer-detail.tpl.html
src/VirtoCommerce.CustomerModule.Web/Scripts/blades/employee-detail.js
src/VirtoCommerce.CustomerModule.Web/Scripts/blades/employee-detail.tpl.html
src/VirtoCommerce.CustomerModule.Web/Scripts/blades/member-detail.js
src/VirtoCommerce.CustomerModule.Web/Scripts/blades/organization-detail.js
src/VirtoCommerce.CustomerModule.Web/Scripts/blades/organization-detail.tpl.html
src/VirtoCommerce.CustomerModule.Web/Scripts/blades/vendor-detail.js
src/VirtoCommerce.CustomerModule.Web/Scripts/blades/vendor-detail.tpl.html

No status field for Organization, Vendor, Employee, Contact.
Add a separated (different status per entity) status field for Organization, Vendor, Employee, Contact.
https://virtocommerce.atlassian.net/browse/VP-6413

VP-6413: Add statuses to Organization, Vendor, Employee, Contact

---

src/VirtoCommerce.CustomerModule.Web/Scripts/blades/customer-accounts-list.js
src/VirtoCommerce.CustomerModule.Web/Scripts/blades/customer-accounts-list.tpl.html
src/VirtoCommerce.CustomerModule.Web/Scripts/blades/filter-detail.js
src/VirtoCommerce.CustomerModule.Web/Scripts/blades/member-detail.js
src/VirtoCommerce.CustomerModule.Web/Scripts/blades/member-emails-list.js
src/VirtoCommerce.CustomerModule.Web/Scripts/blades/member-emails-list.tpl.html
src/VirtoCommerce.CustomerModule.Web/Scripts/blades/member-list.js
src/VirtoCommerce.CustomerModule.Web/Scripts/blades/member-list.tpl.html
src/VirtoCommerce.CustomerModule.Web/Scripts/blades/member-phones-list.js
src/VirtoCommerce.CustomerModule.Web/Scripts/blades/member-phones-list.tpl.html
src/VirtoCommerce.CustomerModule.Web/Scripts/directives/customerSearch.tpl.html

VP-6366: Replace panel action icons

---

src/VirtoCommerce.CustomerModule.Web/Scripts/blades/member-list.tpl.html
src/VirtoCommerce.CustomerModule.Web/Scripts/customer.js

VP-6363: Update icons for Organizations & Contacts blades

---

src/VirtoCommerce.CustomerModule.Web/Scripts/blades/member-list.js
src/VirtoCommerce.CustomerModule.Web/Scripts/customer.js

VP-6768: Security section Replace Key icon

---

src/VirtoCommerce.CustomerModule.Web/Localizations/en.VirtoCommerce.Customer.json

VP-6848 Fix misspelling

---

src/VirtoCommerce.CustomerModule.Web/Scripts/blades/customer-accounts-list.js
src/VirtoCommerce.CustomerModule.Web/Scripts/blades/filter-detail.js
src/VirtoCommerce.CustomerModule.Web/Scripts/blades/pick-store-list.js

VP-6864: Fix header icon

---

src/VirtoCommerce.CustomerModule.Data/Search/Indexing/MemberDocumentBuilder.cs

Jira: https://virtocommerce.atlassian.net/browse/VP-6975

VP-6975: Add new indexing properties to Contact index

---

samples/VirtoCommerce.CustomerSampleModule.Web/Scripts/blades/supplier-detail.js
samples/VirtoCommerce.CustomerSampleModule.Web/Scripts/customerSample.js
samples/VirtoCommerce.CustomerSampleModule.Web/_module.manifest
samples/VirtoCommerce.CustomerSampleModule.Web/package-lock.json
samples/VirtoCommerce.CustomerSampleModule.Web/package.json
samples/VirtoCommerce.CustomerSampleModule.Web/webpack.config.js

Also remove misleading UI: Supplier (Member) can't be created inside Organization as Members don't support them.

VES-43: Restore scripts build in webpack

---

samples/VirtoCommerce.CustomerSampleModule.Web/Model/Supplier.cs
samples/VirtoCommerce.CustomerSampleModule.Web/Module.cs
samples/VirtoCommerce.CustomerSampleModule.Web/Scripts/blades/supplier-detail.tpl.html
samples/VirtoCommerce.CustomerSampleModule.Web/Scripts/customerSample.js
src/VirtoCommerce.CustomerModule.Data/Search/Indexing/MemberDocumentBuilder.cs
src/VirtoCommerce.CustomerModule.Web/Scripts/customer.js

https://virtocommerce.atlassian.net/browse/PT-215

PT-215: Fix Dynamic property indexing for derived types

---

src/VirtoCommerce.CustomerModule.Data/Handlers/LogChangesEventHandler.cs

https://virtocommerce.atlassian.net/browse/PT-201

PT-201: Write “Member“ to OperationLog.ObjectType

---

src/VirtoCommerce.CustomerModule.Web/Scripts/blades/customer-detail.js
src/VirtoCommerce.CustomerModule.Web/Scripts/blades/member-detail.js

https://virtocommerce.atlassian.net/browse/PT-398

PT-398: Fix organizations loading in customer details blade

---

src/VirtoCommerce.CustomerModule.Data/Handlers/SecurtityAccountChangesEventHandler.cs

https://virtocommerce.atlassian.net/browse/PT-481

PT-481: clear cache for both contacts if memberId change was detected

---

src/VirtoCommerce.CustomerModule.Data/Services/MemberService.cs
src/VirtoCommerce.CustomerModule.Web/Scripts/blades/customer-detail.tpl.html
src/VirtoCommerce.CustomerModule.Web/Scripts/customer.js

https://virtocommerce.atlassian.net/browse/PT-148

PT-148 auto compute full name

---

src/VirtoCommerce.CustomerModule.Core/VirtoCommerce.CustomerModule.Core.csproj
src/VirtoCommerce.CustomerModule.Data/VirtoCommerce.CustomerModule.Data.csproj

https://virtocommerce.atlassian.net/browse/PT-207

PT-207: Enable Source link support

---

src/VirtoCommerce.CustomerModule.Web/Scripts/blades/customer-accounts-list.tpl.html

Jira: https://virtocommerce.atlassian.net/browse/PT-839

PT-840: Change default columns for customer-accounts-list.tpl.html

---

src/VirtoCommerce.CustomerModule.Core/Model/Contact.cs
src/VirtoCommerce.CustomerModule.Core/Model/Employee.cs
src/VirtoCommerce.CustomerModule.Core/Model/IHasPersonName.cs
src/VirtoCommerce.CustomerModule.Data/Services/MemberService.cs
src/VirtoCommerce.CustomerModule.Web/Scripts/blades/employee-detail.tpl.html
src/VirtoCommerce.CustomerModule.Web/Scripts/customer.js

https://virtocommerce.atlassian.net/browse/PT-1164

PT-1164 Add FullName auto-compute to Employee

---

src/VirtoCommerce.CustomerModule.Data/Services/MemberService.cs

https://virtocommerce.atlassian.net/browse/PT-1208

PT-1208: remove useless async/await

---

src/VirtoCommerce.CustomerModule.Web/Scripts/customer.js

https://virtocommerce.atlassian.net/browse/PT-641

PT-641 update main menu icon

---

src/VirtoCommerce.CustomerModule.Data/Search/Indexing/MemberDocumentBuilder.cs

https://virtocommerce.atlassian.net/browse/PT-853

PT-855: Search by username

---

src/VirtoCommerce.CustomerModule.Web/Localizations/en.VirtoCommerce.Customer.json
src/VirtoCommerce.CustomerModule.Web/Scripts/blades/member-list.js
src/VirtoCommerce.CustomerModule.Web/Scripts/blades/member-list.tpl.html
src/VirtoCommerce.CustomerModule.Web/Scripts/customer.js
src/VirtoCommerce.CustomerModule.Web/module.manifest

https://virtocommerce.atlassian.net/browse/PT-662

PT-663: Update breadcrumbs

---

src/VirtoCommerce.CustomerModule.Data/Model/ContactEntity.cs

https://virtocommerce.atlassian.net/browse/PT-1472

PT-1473 Set name equals FullName for Contacts

---

src/VirtoCommerce.CustomerModule.Core/VirtoCommerce.CustomerModule.Core.csproj
src/VirtoCommerce.CustomerModule.Data/Search/Indexing/MemberDocumentBuilder.cs
src/VirtoCommerce.CustomerModule.Data/VirtoCommerce.CustomerModule.Data.csproj
src/VirtoCommerce.CustomerModule.Web/VirtoCommerce.CustomerModule.Web.csproj
tests/VirtoCommerce.CustomerModule.Tests/VirtoCommerce.CustomerModule.Tests.csproj

Add IndexDocumentFieldValueType to Document field init

PT-2650 Add mapping by Document Field value type

---

src/VirtoCommerce.CustomerModule.Web/module.manifest

Update platform dependency

---

src/VirtoCommerce.CustomerModule.Core/VirtoCommerce.CustomerModule.Core.csproj
src/VirtoCommerce.CustomerModule.Data/Migrations/20210909184843_AddAddressOuterId.Designer.cs
src/VirtoCommerce.CustomerModule.Data/Migrations/20210909184843_AddAddressOuterId.cs
src/VirtoCommerce.CustomerModule.Data/Model/AddressEntity.cs
src/VirtoCommerce.CustomerModule.Data/Search/Indexing/MemberDocumentBuilder.cs
src/VirtoCommerce.CustomerModule.Data/VirtoCommerce.CustomerModule.Data.csproj
src/VirtoCommerce.CustomerModule.Web/module.manifest

Extend Address with OuterId property
https://virtocommerce.atlassian.net/browse/PT-4062

PT-4060: Extend Address with OuterId property

---

src/VirtoCommerce.CustomerModule.Data/Handlers/LogChangesEventHandler.cs

Refactor LogChangesEventHandler.cs to a single row by using .FromChangedEntry(x, nameof(Member))
https://virtocommerce.atlassian.net/browse/PT-365

PT-365: Refactor LogChangesEventHandler

---

package-lock.json
src/VirtoCommerce.CustomerModule.Core/Model/Vendor.cs
src/VirtoCommerce.CustomerModule.Web/Scripts/customer.js

https://virtocommerce.atlassian.net/browse/PT-5462

PT-5462: Add security accounts to vendor

---

src/VirtoCommerce.CustomerModule.Core/Services/IMemberResolver.cs
src/VirtoCommerce.CustomerModule.Data/Services/MemberResolver.cs
src/VirtoCommerce.CustomerModule.Web/Module.cs
src/VirtoCommerce.CustomerModule.Web/module.manifest

PT-5379: Move MemberResolver from Xapi project

---

src/VirtoCommerce.CustomerModule.Data/Model/ContactEntity.cs

Add mapping for IsAnonymized field
https://virtocommerce.atlassian.net/browse/PT-4714

PT-4714: Add mapping for IsAnonymized field

---

src/VirtoCommerce.CustomerModule.Web/Localizations/en.VirtoCommerce.Customer.json

Fixed and improved language in the EN localization file
https://virtocommerce.atlassian.net/browse/PT-5009

docs: Fix language

---

src/VirtoCommerce.CustomerModule.Data/Handlers/IndexMemberChangedEventHandler.cs
src/VirtoCommerce.CustomerModule.Data/VirtoCommerce.CustomerModule.Data.csproj
src/VirtoCommerce.CustomerModule.Web/module.manifest

Partial search index update support

PT-6527: Partial search index update support

---

src/VirtoCommerce.CustomerModule.Data/Migrations/20220323100943_FixCustomerNameLength.Designer.cs
src/VirtoCommerce.CustomerModule.Data/Migrations/20220323100943_FixCustomerNameLength.cs
src/VirtoCommerce.CustomerModule.Data/Model/ContactEntity.cs
src/VirtoCommerce.CustomerModule.Data/Model/EmployeeEntity.cs
src/VirtoCommerce.CustomerModule.Data/Model/MemberEntity.cs

Fix Customer Name length
https://virtocommerce.atlassian.net/browse/PT-6974

PT-6974: Fix Customer Name length

---

Directory.Build.props
src/VirtoCommerce.CustomerModule.Core/ModuleConstants.cs
src/VirtoCommerce.CustomerModule.Core/Notifications/RegisterCompanyEmailNotification.cs
src/VirtoCommerce.CustomerModule.Core/VirtoCommerce.CustomerModule.Core.csproj
src/VirtoCommerce.CustomerModule.Data/VirtoCommerce.CustomerModule.Data.csproj
src/VirtoCommerce.CustomerModule.Web/Localizations/en.VirtoCommerce.Customer.json
src/VirtoCommerce.CustomerModule.Web/Module.cs
src/VirtoCommerce.CustomerModule.Web/module.manifest

Default organization and contact status settings
https://virtocommerce.atlassian.net/browse/PT-7380

PT-7380: Default organization and contact status settings

---

src/VirtoCommerce.CustomerModule.Web/Scripts/common/blades/address-detail.js

https://virtocommerce.atlassian.net/browse/PT-6256

PT-6256: default address reset fix and refactoring

---

src/VirtoCommerce.CustomerModule.Core/Model/IconResizeRequest.cs
src/VirtoCommerce.CustomerModule.Core/Model/Member.cs
src/VirtoCommerce.CustomerModule.Core/Services/IIconService.cs
src/VirtoCommerce.CustomerModule.Core/VirtoCommerce.CustomerModule.Core.csproj
src/VirtoCommerce.CustomerModule.Data/Migrations/20220713070428_AddMemberIcon.Designer.cs
src/VirtoCommerce.CustomerModule.Data/Migrations/20220713070428_AddMemberIcon.cs
src/VirtoCommerce.CustomerModule.Data/Model/MemberEntity.cs
src/VirtoCommerce.CustomerModule.Data/Services/IconService.cs
src/VirtoCommerce.CustomerModule.Data/VirtoCommerce.CustomerModule.Data.csproj
src/VirtoCommerce.CustomerModule.Web/Controllers/Api/CustomerModuleController.cs
src/VirtoCommerce.CustomerModule.Web/Localizations/en.VirtoCommerce.Customer.json
src/VirtoCommerce.CustomerModule.Web/Module.cs
src/VirtoCommerce.CustomerModule.Web/Scripts/blades/member-icon.js
src/VirtoCommerce.CustomerModule.Web/Scripts/blades/member-icon.tpl.html
src/VirtoCommerce.CustomerModule.Web/Scripts/blades/member-list.tpl.html
src/VirtoCommerce.CustomerModule.Web/Scripts/customer.js
src/VirtoCommerce.CustomerModule.Web/Scripts/widgets/memberIconWidget.js
src/VirtoCommerce.CustomerModule.Web/Scripts/widgets/memberIconWidget.tpl.html
src/VirtoCommerce.CustomerModule.Web/module.manifest

Member icon uploading and displaying
https://virtocommerce.atlassian.net/browse/PT-8145

PT-8145: Member icon uploading and displaying

---

src/VirtoCommerce.CustomerModule.Web/Scripts/common/blades/address-detail.tpl.html

the region has been changed to an optional field
https://virtocommerce.atlassian.net/browse/PT-8313

the region has been changed to an optional field

---

src/VirtoCommerce.CustomerModule.Data/Migrations/20220802111623_SetCountryNameNotRequared.Designer.cs
src/VirtoCommerce.CustomerModule.Data/Migrations/20220802111623_SetCountryNameNotRequared.cs
src/VirtoCommerce.CustomerModule.Data/Model/AddressEntity.cs

This change is necessary for updating XApi
https://virtocommerce.atlassian.net/browse/PT-4414

PT-4414: CountryName and RegionName Set Not Required

---

src/VirtoCommerce.CustomerModule.Core/VirtoCommerce.CustomerModule.Core.csproj
src/VirtoCommerce.CustomerModule.Data/Services/MemberService.cs
src/VirtoCommerce.CustomerModule.Data/VirtoCommerce.CustomerModule.Data.csproj
src/VirtoCommerce.CustomerModule.Web/VirtoCommerce.CustomerModule.Web.csproj
tests/VirtoCommerce.CustomerModule.Tests/MemberServiceUnitTests.cs

Fill country and region name in addresses
https://virtocommerce.atlassian.net/browse/PT-8609

PT-8609: Fill country and region name in addresses

---

src/VirtoCommerce.CustomerModule.Web/Content/css/customer.css
src/VirtoCommerce.CustomerModule.Web/Content/customer.css
src/VirtoCommerce.CustomerModule.Web/Scripts/directives/customerSearch.tpl.html

https://virtocommerce.atlassian.net/browse/PT-7777

PT-7777: Filter dropdown UI update

---

src/VirtoCommerce.CustomerModule.Web/Scripts/blades/member-detail.js

https://virtocommerce.atlassian.net/browse/PT-6498

PT-6498: Address save fix

---

src/VirtoCommerce.CustomerModule.Data/Search/Indexing/MemberDocumentChangesProvider.cs
src/VirtoCommerce.CustomerModule.Data/VirtoCommerce.CustomerModule.Data.csproj
src/VirtoCommerce.CustomerModule.Web/module.manifest

https://virtocommerce.atlassian.net/browse/PT-9555

PT-9555: partial indexation error fix

---

src/VirtoCommerce.CustomerModule.Web/Controllers/Api/CustomerModuleController.cs

https://virtocommerce.atlassian.net/browse/PT-8372

PT-8372: Fix possiblity to set Billing&Shipping address as default via API

---

src/VirtoCommerce.CustomerModule.Core/Model/Search/MembersSearchCriteria.cs
src/VirtoCommerce.CustomerModule.Data/Services/MemberSearchService.cs

Allow to search by OuterIds

---

src/VirtoCommerce.CustomerModule.Data/Search/Indexing/MemberDocumentBuilder.cs

feat: Add OuterId into full-text search index
https://virtocommerce.atlassian.net/browse/PT-10594

PT-10594: Add OuterId into full-text search index

---

src/VirtoCommerce.CustomerModule.Web/Scripts/blades/member-detail.js

https://virtocommerce.atlassian.net/browse/PT-10038

PT-10038: Fix error with organizations from the second level

---

src/VirtoCommerce.CustomerModule.Data/Services/MemberResolver.cs

Fix disposing of UserManager in the MemberResolver service

Fix disposing UserManager

---

src/VirtoCommerce.CustomerModule.Web/package-lock.json
src/VirtoCommerce.CustomerModule.Web/package.json
src/VirtoCommerce.CustomerModule.Web/webpack.config.js

feat: add nodejs-lts support
https://virtocommerce.atlassian.net/browse/PT-9395

PT-9395: add nodejs-lts support

---

src/VirtoCommerce.CustomerModule.Web/Controllers/Api/CustomerModuleController.cs

fix: Rest API returns Unauthorized instead of Forbid.
https://virtocommerce.atlassian.net/browse/PT-12269

PT-12269: Rest API returns Unauthorized instead of Forbid.

---

src/VirtoCommerce.CustomerModule.Data/Services/MemberSearchService.cs
src/VirtoCommerce.CustomerModule.Data/Services/MemberService.cs

PT-12523: Add security cache region cache expiration

---

.editorconfig
.gitattributes
Directory.Build.props
VirtoCommerce.CustomerModule.sln.DotSettings
module.ignore
samples/VirtoCommerce.CustomerSampleModule.Web/VirtoCommerce.CustomerSampleModule.Web.csproj
src/VirtoCommerce.CustomerModule.Core/VirtoCommerce.CustomerModule.Core.csproj
src/VirtoCommerce.CustomerModule.Data.MySql/VirtoCommerce.CustomerModule.Data.MySql.csproj
src/VirtoCommerce.CustomerModule.Data.PostgreSql/VirtoCommerce.CustomerModule.Data.PostgreSql.csproj
src/VirtoCommerce.CustomerModule.Data.SqlServer/VirtoCommerce.CustomerModule.Data.SqlServer.csproj
src/VirtoCommerce.CustomerModule.Data/ExportImport/CustomerExportImport.cs
src/VirtoCommerce.CustomerModule.Data/Handlers/IndexMemberChangedEventHandler.cs
src/VirtoCommerce.CustomerModule.Data/Search/Indexing/MemberDocumentBuilder.cs
src/VirtoCommerce.CustomerModule.Data/Search/MemberSearchRequestBuilder.cs
src/VirtoCommerce.CustomerModule.Data/Services/IconService.cs
src/VirtoCommerce.CustomerModule.Data/VirtoCommerce.CustomerModule.Data.csproj
src/VirtoCommerce.CustomerModule.Web/Module.cs
src/VirtoCommerce.CustomerModule.Web/VirtoCommerce.CustomerModule.Web.csproj
src/VirtoCommerce.CustomerModule.Web/module.manifest
tests/VirtoCommerce.CustomerModule.Tests/LogChangesMemberChangedEventHandlerTests.cs
tests/VirtoCommerce.CustomerModule.Tests/VirtoCommerce.CustomerModule.Tests.csproj

https://virtocommerce.atlassian.net/browse/PT-10449

PT-10449: Update Crud and Search services

---

src/VirtoCommerce.CustomerModule.Data/Search/MemberSearchRequestBuilder.cs

https://virtocommerce.atlassian.net/browse/PT-12924

PT-12924: Fix search criteria corruption

---

src/VirtoCommerce.CustomerModule.Data/Search/Indexing/MemberDocumentBuilder.cs
src/VirtoCommerce.CustomerModule.Data/VirtoCommerce.CustomerModule.Data.csproj
src/VirtoCommerce.CustomerModule.Web/module.manifest

feat: Implement IIndexSchemaBuilder
https://virtocommerce.atlassian.net/browse/PT-13040

PT-13040: Implement IIndexSchemaBuilder

---

src/VirtoCommerce.CustomerModule.Core/VirtoCommerce.CustomerModule.Core.csproj
src/VirtoCommerce.CustomerModule.Data/Repositories/CustomerDbContext.cs
src/VirtoCommerce.CustomerModule.Data/VirtoCommerce.CustomerModule.Data.csproj
src/VirtoCommerce.CustomerModule.Web/module.manifest

fix: DateTime values coming back from the SqlServer database always have a DateTimeKind of Unspecified.
https://virtocommerce.atlassian.net/browse/PT-13179

PT-13179: DateTime values coming back from the SqlServer database always have a DateTimeKind of Unspecified

---

src/VirtoCommerce.CustomerModule.Data/Model/MemberEntity.cs

PT-13751: Add virtual methods to member entity

---

src/VirtoCommerce.CustomerModule.Web/Localizations/en.VirtoCommerce.Customer.json
src/VirtoCommerce.CustomerModule.Web/Scripts/customer.js
src/VirtoCommerce.CustomerModule.Web/Scripts/widgets/organizationAssetsWidget.js
src/VirtoCommerce.CustomerModule.Web/Scripts/widgets/organizationAssetsWidget.tpl.html

https://virtocommerce.atlassian.net/browse/PT-13731

PT-13731: add assets to organization

---

Directory.Build.props
samples/VirtoCommerce.CustomerSampleModule.Web/VirtoCommerce.CustomerSampleModule.Web.csproj
src/VirtoCommerce.CustomerModule.Core/VirtoCommerce.CustomerModule.Core.csproj
src/VirtoCommerce.CustomerModule.Data.MySql/VirtoCommerce.CustomerModule.Data.MySql.csproj
src/VirtoCommerce.CustomerModule.Data.PostgreSql/VirtoCommerce.CustomerModule.Data.PostgreSql.csproj
src/VirtoCommerce.CustomerModule.Data.SqlServer/VirtoCommerce.CustomerModule.Data.SqlServer.csproj
src/VirtoCommerce.CustomerModule.Data/VirtoCommerce.CustomerModule.Data.csproj
src/VirtoCommerce.CustomerModule.Web/VirtoCommerce.CustomerModule.Web.csproj
src/VirtoCommerce.CustomerModule.Web/module.manifest
tests/VirtoCommerce.CustomerModule.Tests/VirtoCommerce.CustomerModule.Tests.csproj

https://virtocommerce.atlassian.net/browse/PT-14740
https://vc3prerelease.blob.core.windows.net/packages/CustomerSampleModule.Web-sample-VirtoCommerce.CustomerModule.3.800.0-pr-230-08b8.zip

PT-14740: .net 8

---

src/VirtoCommerce.CustomerModule.Core/Services/IFavoriteAddressService.cs
src/VirtoCommerce.CustomerModule.Data.MySql/Migrations/20240207190425_AddFavoriteAddress.Designer.cs
src/VirtoCommerce.CustomerModule.Data.MySql/Migrations/20240207190425_AddFavoriteAddress.cs
src/VirtoCommerce.CustomerModule.Data.MySql/Migrations/CustomerDbContextModelSnapshot.cs
src/VirtoCommerce.CustomerModule.Data.PostgreSql/Migrations/20240207190440_AddFavoriteAddress.Designer.cs
src/VirtoCommerce.CustomerModule.Data.PostgreSql/Migrations/20240207190440_AddFavoriteAddress.cs
src/VirtoCommerce.CustomerModule.Data.PostgreSql/Migrations/CustomerDbContextModelSnapshot.cs
src/VirtoCommerce.CustomerModule.Data.SqlServer/Migrations/20240207141246_AddFavoriteAddress.Designer.cs
src/VirtoCommerce.CustomerModule.Data.SqlServer/Migrations/20240207141246_AddFavoriteAddress.cs
src/VirtoCommerce.CustomerModule.Data/Caching/FavoriteAddressCacheRegion.cs
src/VirtoCommerce.CustomerModule.Data/Model/FavoriteAddressEntity.cs
src/VirtoCommerce.CustomerModule.Data/Repositories/CustomerDbContext.cs
src/VirtoCommerce.CustomerModule.Data/Repositories/IMemberRepository.cs
src/VirtoCommerce.CustomerModule.Data/Repositories/MemberRepositoryBase.cs
src/VirtoCommerce.CustomerModule.Data/Services/FavoriteAddressService.cs
src/VirtoCommerce.CustomerModule.Web/Module.cs

https://virtocommerce.atlassian.net/browse/VCST-327
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Customer_3.801.0-pr-233-7e6a.zip

VCST-327: Add favorite addresses

---

src/VirtoCommerce.CustomerModule.Web/Controllers/Api/CustomerModuleController.cs
src/VirtoCommerce.CustomerModule.Web/Scripts/customer.js
src/VirtoCommerce.CustomerModule.Web/Scripts/resources/members.js

feat: Add GET members/user/{userId} endpoint to request member by user Id.
https://virtocommerce.atlassian.net/browse/VCST-630
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Customer_3.803.0-pr-235-9db5.zip
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Customer_3.802.0-pr-235-ab12.zip

VCST-630: Add GetMemberByUserId

---

src/VirtoCommerce.CustomerModule.Data.MySql/Migrations/20240531112300_ResizeAddressOrganization.Designer.cs
src/VirtoCommerce.CustomerModule.Data.MySql/Migrations/20240531112300_ResizeAddressOrganization.cs
src/VirtoCommerce.CustomerModule.Data.PostgreSql/Migrations/20240531112237_ResizeAddressOrganization.Designer.cs
src/VirtoCommerce.CustomerModule.Data.PostgreSql/Migrations/20240531112237_ResizeAddressOrganization.cs
src/VirtoCommerce.CustomerModule.Data.PostgreSql/Migrations/CustomerDbContextModelSnapshot.cs
src/VirtoCommerce.CustomerModule.Data.SqlServer/Migrations/20240531112051_ResizeAddressOrganization.Designer.cs
src/VirtoCommerce.CustomerModule.Data.SqlServer/Migrations/20240531112051_ResizeAddressOrganization.cs
src/VirtoCommerce.CustomerModule.Data.SqlServer/Migrations/CustomerDbContextModelSnapshot.cs
src/VirtoCommerce.CustomerModule.Data/Model/AddressEntity.cs

- Resize AddressEntity Organization field according to MemberEntity Name
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Customer_3.808.0-pr-243-c21f.zip

feat: Resize address Organization field according to member Name

---

src/VirtoCommerce.CustomerModule.Data/Search/Indexing/MemberDocumentChangesProvider.cs

fix: ChangeLogSearchCriteria added virtual method for search criteria
https://virtocommerce.atlassian.net/browse/VCST-1413
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Customer_3.810.0-pr-246-9d15.zip

VCST-1413: ChangeLogSearchCriteria added virtual method for search criteria

---

VirtoCommerce.CustomerModule.sln.DotSettings
samples/VirtoCommerce.CustomerSampleModule.Web/VirtoCommerce.CustomerSampleModule.Web.csproj
src/VirtoCommerce.CustomerModule.Core/Extensions/ClaimsPrincipalExtensions.cs
src/VirtoCommerce.CustomerModule.Core/ModuleConstants.cs
src/VirtoCommerce.CustomerModule.Core/VirtoCommerce.CustomerModule.Core.csproj
src/VirtoCommerce.CustomerModule.Data.MySql/VirtoCommerce.CustomerModule.Data.MySql.csproj
src/VirtoCommerce.CustomerModule.Data.PostgreSql/VirtoCommerce.CustomerModule.Data.PostgreSql.csproj
src/VirtoCommerce.CustomerModule.Data.SqlServer/VirtoCommerce.CustomerModule.Data.SqlServer.csproj
src/VirtoCommerce.CustomerModule.Data/OpenIddict/Constants.cs
src/VirtoCommerce.CustomerModule.Data/OpenIddict/ErrorDescriber.cs
src/VirtoCommerce.CustomerModule.Data/OpenIddict/OrganizationIdClaimProvider.cs
src/VirtoCommerce.CustomerModule.Data/OpenIddict/OrganizationIdRequestValidator.cs
src/VirtoCommerce.CustomerModule.Data/VirtoCommerce.CustomerModule.Data.csproj
src/VirtoCommerce.CustomerModule.Web/Module.cs
src/VirtoCommerce.CustomerModule.Web/module.manifest

https://virtocommerce.atlassian.net/browse/VCST-1353
https://vc3prerelease.blob.core.windows.net/packages/SampleModule.Web-sample-VirtoCommerce.CustomerModule.3.811.0-pr-247-f3c6.zip

VCST-1353: Store current organization ID in claims

---

src/VirtoCommerce.CustomerModule.Web/Localizations/en.VirtoCommerce.Customer.json
src/VirtoCommerce.CustomerModule.Web/Scripts/blades/member-list.js
src/VirtoCommerce.CustomerModule.Web/Scripts/blades/member-list.tpl.html
src/VirtoCommerce.CustomerModule.Web/Scripts/customer.js

feat: Addes Routes for Companies and Contacts. It helps manage Companies and Contacts better, makes it easier to search for ID, and allows us to copy the links.
feat:: Added copy id, copy name
https://virtocommerce.atlassian.net/browse/VCST-415
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Customer_3.812.0-pr-248-f112.zip

VCST-415: Routes for Companies and Contacts

---

src/VirtoCommerce.CustomerModule.Core/Model/Contact.cs
src/VirtoCommerce.CustomerModule.Core/Model/Employee.cs
src/VirtoCommerce.CustomerModule.Data.SqlServer/Migrations/20240826132046_AddDefaultOrganization.Designer.cs
src/VirtoCommerce.CustomerModule.Data.SqlServer/Migrations/20240826132046_AddDefaultOrganization.cs
src/VirtoCommerce.CustomerModule.Data/Model/ContactEntity.cs
src/VirtoCommerce.CustomerModule.Data/Model/EmployeeEntity.cs
src/VirtoCommerce.CustomerModule.Data/OpenIddict/OrganizationIdClaimProvider.cs
src/VirtoCommerce.CustomerModule.Data/Repositories/CustomerDbContext.cs
src/VirtoCommerce.CustomerModule.Web/Localizations/en.VirtoCommerce.Customer.json
src/VirtoCommerce.CustomerModule.Web/Scripts/blades/customer-detail.tpl.html
src/VirtoCommerce.CustomerModule.Web/Scripts/blades/employee-detail.tpl.html
src/VirtoCommerce.CustomerModule.Web/Scripts/blades/member-detail.js
src/VirtoCommerce.CustomerModule.Web/Scripts/customer.js

https://virtocommerce.atlassian.net/browse/VCST-1402
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Customer_3.813.0-pr-249-aeca.zip

VCST-1402: add default organization to customer, employee

---

src/VirtoCommerce.CustomerModule.Data.MySql/Migrations/20240829163335_AddDefaultOrganization.Designer.cs
src/VirtoCommerce.CustomerModule.Data.MySql/Migrations/20240829163335_AddDefaultOrganization.cs
src/VirtoCommerce.CustomerModule.Data.MySql/Migrations/CustomerDbContextModelSnapshot.cs
src/VirtoCommerce.CustomerModule.Data.PostgreSql/Migrations/20240829163242_AddDefaultOrganization.Designer.cs
src/VirtoCommerce.CustomerModule.Data.PostgreSql/Migrations/20240829163242_AddDefaultOrganization.cs

https://virtocommerce.atlassian.net/browse/VCST-1402
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Customer_3.813.0-pr-250-60d8.zip

VCST-1402: add DefaultOrganizationId migrations

---

src/VirtoCommerce.CustomerModule.Web/Scripts/blades/member-list.js
src/VirtoCommerce.CustomerModule.Web/Scripts/directives/customerSearch.tpl.html

feat: Implemented default relevance sorting for keyword searches. This enhancement ensures that search results are more relevant to the user's query. The next click in the grid enables custom sorting for the search results.
https://virtocommerce.atlassian.net/browse/VCST-1856
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Customer_3.815.0-pr-252-a103.zip

VCST-1856: Search by keyword use relevance sorting by default

---

Directory.Build.props
src/VirtoCommerce.CustomerModule.Core/Model/Member.cs
src/VirtoCommerce.CustomerModule.Core/VirtoCommerce.CustomerModule.Core.csproj
src/VirtoCommerce.CustomerModule.Data/Search/MemberIndexedSearchService.cs
src/VirtoCommerce.CustomerModule.Data/VirtoCommerce.CustomerModule.Data.csproj
src/VirtoCommerce.CustomerModule.Web/module.manifest

https://virtocommerce.atlassian.net/browse/VCST-1454
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Customer_3.816.0-pr-253-ae5f.zip

VCST-1454: add relevance score to Member

---

src/VirtoCommerce.CustomerModule.Web/Scripts/blades/member-detail.js

parentBlade is null when contact details blade is open by the direct url 
https://virtocommerce.atlassian.net/browse/VCST-1979
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Customer_3.818.0-pr-254-fcb4.zip

VCST-1979: check if parentBlade is null

---

src/VirtoCommerce.CustomerModule.Web/Scripts/blades/member-detail.js

https://virtocommerce.atlassian.net/browse/VCST-2555
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Customer_3.823.0-pr-261-b98e.zip

VCST-2555: load inner organizations for default organizations list

---

src/VirtoCommerce.CustomerModule.Data/Services/MemberService.cs

- Add virtual methods to MemberService as in a platform CrudService
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Customer_3.825.0-pr-266-8d29.zip

feat: Add virtual methods to MemberService

---

src/VirtoCommerce.CustomerModule.Core/Model/Contact.cs
src/VirtoCommerce.CustomerModule.Web/Controllers/Api/CustomerModuleController.cs

feat: Support partial updates for Member, Contact, Organization entities using PATCH endpoint
New methods were added to platform API:
* PATCH api/members/{id}
* PATCH api/contacts/{id}
* PATCH api/organizations/{id}
All of them receive a special json object that describes the operations performed on the fields.
Example JSON Patch Request
```json
[
{ "op": "add", "path": "/newField", "value": "New Value" },
{ "op": "remove", "path": "/oldField" },
{ "op": "replace", "path": "/existingField", "value": "Updated Value" },
{ "op": "move", "from": "/tempField", "path": "/finalField" },
{ "op": "copy", "from": "/sourceField", "path": "/destinationField" },
{ "op": "test", "path": "/testField", "value": "Expected Value" }
]
```
add - to add an element to an array
remove - to remove an element …

VCST-3134: Support partial updates for entities using PATCH endpoint

---

src/VirtoCommerce.CustomerModule.Core/Events/CustomerPreferenceChangedEvent.cs
src/VirtoCommerce.CustomerModule.Core/Events/CustomerPreferenceChangingEvent.cs
src/VirtoCommerce.CustomerModule.Core/Extensions/CustomerPreferenceServiceExtensions.cs
src/VirtoCommerce.CustomerModule.Core/Model/Contact.cs
src/VirtoCommerce.CustomerModule.Core/Model/CustomerPreference.cs
src/VirtoCommerce.CustomerModule.Core/Model/CustomerPreferenceSearchCriteria.cs
src/VirtoCommerce.CustomerModule.Core/Model/CustomerPreferenceSearchResult.cs
src/VirtoCommerce.CustomerModule.Core/Services/ICustomerPreferenceCrudService.cs
src/VirtoCommerce.CustomerModule.Core/Services/ICustomerPreferenceSearchService.cs
src/VirtoCommerce.CustomerModule.Core/Services/ICustomerPreferenceService.cs
src/VirtoCommerce.CustomerModule.Data.MySql/Migrations/20250605144726_AddCustomerPreferences.Designer.cs
src/VirtoCommerce.CustomerModule.Data.MySql/Migrations/20250605144726_AddCustomerPreferences.cs
src/VirtoCommerce.CustomerModule.Data.MySql/Migrations/CustomerDbContextModelSnapshot.cs
src/VirtoCommerce.CustomerModule.Data.PostgreSql/Migrations/20250605144711_AddCustomerPreferences.Designer.cs
src/VirtoCommerce.CustomerModule.Data.PostgreSql/Migrations/20250605144711_AddCustomerPreferences.cs
src/VirtoCommerce.CustomerModule.Data.PostgreSql/Migrations/CustomerDbContextModelSnapshot.cs
src/VirtoCommerce.CustomerModule.Data.SqlServer/Migrations/20250605130328_AddCustomerPreferences.Designer.cs
src/VirtoCommerce.CustomerModule.Data.SqlServer/Migrations/20250605130328_AddCustomerPreferences.cs
src/VirtoCommerce.CustomerModule.Data/Model/ContactEntity.cs
src/VirtoCommerce.CustomerModule.Data/Model/CustomerPreferenceEntity.cs
src/VirtoCommerce.CustomerModule.Data/Repositories/CustomerDbContext.cs
src/VirtoCommerce.CustomerModule.Data/Repositories/CustomerRepository.cs
src/VirtoCommerce.CustomerModule.Data/Repositories/ICustomerRepository.cs
src/VirtoCommerce.CustomerModule.Data/Services/CustomerPreferenceCrudService.cs
src/VirtoCommerce.CustomerModule.Data/Services/CustomerPreferenceSearchService.cs
src/VirtoCommerce.CustomerModule.Data/Services/CustomerPreferenceService.cs
src/VirtoCommerce.CustomerModule.Web/Controllers/Api/CustomerPreferenceController.cs
src/VirtoCommerce.CustomerModule.Web/Module.cs

https://virtocommerce.atlassian.net/browse/VCST-3294
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Customer_3.832.0-pr-273-4655.zip

VCST-3294: Add customer preferences

---

src/VirtoCommerce.CustomerModule.Core/ModuleConstants.cs

feat: Enable event-based indexation by default
https://virtocommerce.atlassian.net/browse/VCST-4016
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Customer_3.838.0-pr-278-cd8e.zip

VCST-4016: Enable event-based indexation by default

---

src/VirtoCommerce.CustomerModule.Core/Model/Member.cs
src/VirtoCommerce.CustomerModule.Core/VirtoCommerce.CustomerModule.Core.csproj
src/VirtoCommerce.CustomerModule.Data.MySql/VirtoCommerce.CustomerModule.Data.MySql.csproj
src/VirtoCommerce.CustomerModule.Data.PostgreSql/VirtoCommerce.CustomerModule.Data.PostgreSql.csproj
src/VirtoCommerce.CustomerModule.Data.SqlServer/VirtoCommerce.CustomerModule.Data.SqlServer.csproj
src/VirtoCommerce.CustomerModule.Data/VirtoCommerce.CustomerModule.Data.csproj
src/VirtoCommerce.CustomerModule.Web/module.manifest

feat: Added DynamicPropertyAccessor support
https://virtocommerce.atlassian.net/browse/VCST-3638
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Customer_3.839.0-pr-280-79f6.zip

VCST-3638: Added DynamicPropertyAccessor
